---
# Some binaries aren't listed here due they will be installed directly from
# other modules commands
binaries_to_install:
  - ansible
  - exiftool
  - ffmpeg
  - fzf
  - lf
  - p7zip
  - postgresql
  - rename
  - rust
  - thefuck
  - tldr
  - tree
  - webp
  - youtube-dl

# Apps installed using Homebrew-cask. Some apps aren't listed here due they
# will be installed directly from the App store or they come preinstalled
apps_to_install:
  - adobe-acrobat-reader # ü§¶‚Äç
  - affinity
  - autofirma # ü§¶‚Äç
  - bitwarden
  - calibre
  - cyberduck
  - dash
  - docker
  - doxie
  - eloston-chromium
  - figma
  - firefox
  - framer
  - google-chrome
  - handbrake-app
  - imageoptim
  - logi-options+
  - loom
  - mullvad-vpn
  - nextcloud
  - notion
  - obsidian
  - ogdesign-eagle
  - postman
  - qlcolorcode
  - qlmarkdown
  - qlstephen
  - raycast
  - screen-studio
  - slack
  - spotify
  - stremio
  - telegram
  - topaz
  - tor-browser
  - transmission
  - vlc
  - yubico-authenticator

# From Homebrew-fonts
fonts_to_install:
  - font-geist
  - font-geist-mono
  - font-host-grotesk
  - font-ibm-plex
  - font-instrument-sans
  - font-instrument-serif
  - font-inter
  - font-libre-baskerville
  - font-roboto
  - font-sf-pro