# Starship Prompt Configuration
# See https://starship.rs/config/ for full documentation

# Directory module - shows the current directory
add_newline = true
command_timeout = 200
format = "[$directory$git_branch$git_status]($style)$character"

# Directory module - shows the current directory
[directory]
truncation_length = 3
truncate_to_repo = true
format = "[$path](bold purple) "

# Character module - shows the prompt character
[character]
error_symbol = "[✗](#56c4af)"
success_symbol = "[❯](#56c4af)"

# Git branch module - shows the current git branch
[git_branch]
style = "bold #E2C08D"

# Git status module - shows the git status
[git_status]
disabled = true